name: Build and deploy website

on:
  push:
    branches:
      - main

permissions:
  pages: write
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Cache clojure/java dependencies
    #   uses: "actions/cache@v2"
    #   with:
    #     path: |
    #       ~/.m2/repository
    #       ~/.gitlibs
    #       ~/.deps.clj
    #     key: "${{ runner.os }}-clojure-${{ hashFiles('deps.edn') }}"
    #     restore-keys: "${{ runner.os }}-clojure-"

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - run: npm install

    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@master
      with:
        cli: '1.11.1.1208'

    - id: install-aws-cli
      uses: unfor19/install-aws-cli-action@v1.0.7
      with:
        version: 2
        verbose: false
        arch: amd64
        rootdir: ""
        workdir: ""

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: eu-west-1

    - name: Build
      run: make target/site

    - name: Deploy
      run: ./deploy.sh
